server:
  port: 9001
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: hiber-biz
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sundry_biz?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: xxxxxx
    driver-class-name: com.mysql.jdbc.Driver
  activiti:
    check-process-definitions: false